-- Extend the existing newsletter subscriber storage without deleting historical rows.
CREATE TYPE "NewsletterStatus" AS ENUM ('pending', 'active', 'unsubscribed', 'bounced', 'complained');
CREATE TYPE "NewsletterFrequency" AS ENUM ('immediate', 'weekly', 'monthly');
CREATE TYPE "NewsletterGoalType" AS ENUM ('hypertrophy', 'fat_loss', 'strength', 'general_fitness');
CREATE TYPE "NewsletterLanguage" AS ENUM ('fr', 'en');

ALTER TABLE "NewsletterSubscriber" RENAME TO "newsletter_subscribers";
ALTER TABLE "newsletter_subscribers"
  ADD COLUMN "status" "NewsletterStatus" NOT NULL DEFAULT 'pending',
  ADD COLUMN "language" "NewsletterLanguage" NOT NULL DEFAULT 'en',
  ADD COLUMN "consentAt" TIMESTAMP(3),
  ADD COLUMN "consentTextVersion" TEXT,
  ADD COLUMN "consentSource" TEXT,
  ADD COLUMN "confirmedAt" TIMESTAMP(3),
  ADD COLUMN "unsubscribedAt" TIMESTAMP(3),
  ADD COLUMN "confirmationToken" TEXT,
  ADD COLUMN "preferencesToken" TEXT;

-- UUIDs are generated by PostgreSQL for legacy rows; all new tokens are 256-bit values generated by Node crypto.
UPDATE "newsletter_subscribers"
SET "confirmationToken" = gen_random_uuid()::text || gen_random_uuid()::text,
    "preferencesToken" = gen_random_uuid()::text || gen_random_uuid()::text;

ALTER TABLE "newsletter_subscribers"
  ALTER COLUMN "confirmationToken" SET NOT NULL,
  ALTER COLUMN "preferencesToken" SET NOT NULL;

ALTER INDEX "NewsletterSubscriber_pkey" RENAME TO "newsletter_subscribers_pkey";
ALTER INDEX "NewsletterSubscriber_email_key" RENAME TO "newsletter_subscribers_email_key";
ALTER INDEX "NewsletterSubscriber_createdAt_idx" RENAME TO "newsletter_subscribers_createdAt_idx";

CREATE UNIQUE INDEX "newsletter_subscribers_confirmationToken_key" ON "newsletter_subscribers"("confirmationToken");
CREATE UNIQUE INDEX "newsletter_subscribers_preferencesToken_key" ON "newsletter_subscribers"("preferencesToken");
CREATE INDEX "newsletter_subscribers_status_language_idx" ON "newsletter_subscribers"("status", "language");

CREATE TABLE "newsletter_preferences" (
  "id" TEXT NOT NULL,
  "subscriberId" TEXT NOT NULL,
  "newArticles" BOOLEAN NOT NULL DEFAULT true,
  "strengthTraining" BOOLEAN NOT NULL DEFAULT true,
  "workoutPrograms" BOOLEAN NOT NULL DEFAULT true,
  "nutrition" BOOLEAN NOT NULL DEFAULT true,
  "supplements" BOOLEAN NOT NULL DEFAULT true,
  "equipment" BOOLEAN NOT NULL DEFAULT true,
  "tools" BOOLEAN NOT NULL DEFAULT true,
  "guides" BOOLEAN NOT NULL DEFAULT true,
  "frequency" "NewsletterFrequency" NOT NULL DEFAULT 'weekly',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "newsletter_preferences_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "newsletter_preferences_subscriberId_fkey" FOREIGN KEY ("subscriberId") REFERENCES "newsletter_subscribers"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "newsletter_preferences_subscriberId_key" ON "newsletter_preferences"("subscriberId");
CREATE INDEX "newsletter_preferences_nutrition_frequency_idx" ON "newsletter_preferences"("nutrition", "frequency");
CREATE INDEX "newsletter_preferences_strengthTraining_frequency_idx" ON "newsletter_preferences"("strengthTraining", "frequency");

-- Give historical subscribers the same defaults as new subscriptions.
INSERT INTO "newsletter_preferences" ("id", "subscriberId", "updatedAt")
SELECT 'legacy_' || "id", "id", CURRENT_TIMESTAMP FROM "newsletter_subscribers";

CREATE TABLE "newsletter_subscriber_goals" (
  "id" TEXT NOT NULL,
  "subscriberId" TEXT NOT NULL,
  "goal" "NewsletterGoalType" NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "newsletter_subscriber_goals_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "newsletter_subscriber_goals_subscriberId_fkey" FOREIGN KEY ("subscriberId") REFERENCES "newsletter_subscribers"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "newsletter_subscriber_goals_subscriberId_goal_key" ON "newsletter_subscriber_goals"("subscriberId", "goal");
CREATE INDEX "newsletter_subscriber_goals_goal_subscriberId_idx" ON "newsletter_subscriber_goals"("goal", "subscriberId");
